### ISSUE TITLE
SQL file

### ISSUE THREAD

**Issue by stevencreek** [prajwal051290/Facebook-Prototype#1]
Hey prajwal, I was looking for a demo project which works with mysql. I have been working with mongo but was looking for mysql connection with node. I found this very helpful to understand the flow.
Can you help me with the sql file because its tough to understand all the queries and relationship. If you can provide sql file it would be great.
stevencreek001@gmail.com

Hope you can help.
Thank you
Steven

**Comment by prajwal051290** [comment]
Hey Steven,

Sorry for late reply!

Please check sql file here: https://github.com/prajwal051290/Facebook-MySQL/blob/master/FB4/routes/queryExecutor.js

Also check signUp function from index.js. All the functiond from index.js call fetchData() function which essentially fetches data from mysql. fecthData is defined in 'queryExecutor.js'. Please make sure you have mysql module of node.js installed in your workspace. 

Please let me know if this helps!
- Prajwal Kondawar

**Comment by stevencreek** [comment]
Hey I found that but what I am asking here is the database tables .SQL file.
maybe you can export it from your mysql workbench and share.
I understood the entire flow but I want to look over the sql tables like
how are they seperated and how are they organized.

Hope you can help
Thank you
Steven

On Mon, Mar 14, 2016 at 12:51 PM, Prajwal Kondawar <notifications@github.com

**Comment by prajwal051290** [comment]
Ohh!!! I am sorry to say but I do not have the DB schema with me now. It was on old laptop which crashed.

**Comment by stevencreek** [comment]
Oh thats sad to hear.
Anyways thank you for the post.

cheers
Steven
